### ISSUE TITLE
Abstraction: Simply Switch-Case

### ISSUE THREAD

**Issue by jwood36** [Marinarra/TicTacToe#4]
You perform the same operation over and over, the only thing that changes is the @coordinate value comparison

>             switch (coordinate)
>             {
>                 case 1:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 2:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 3:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 4:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 5:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 6:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 7:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 8:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 case 9:
>                     board[coordinate - 1] = flag;   <========= DUPLICATE
>                     break;
>                 default:
>                     return false;
>             }
>

**Comment by Marinarra** [comment]
I changed the switch-case statements in Board to simplified if-else statements in the QA branch.
