### ISSUE TITLE
Logic - Program.convertAscii

### ISSUE THREAD

**Issue by jwood36** [Marinarra/TicTacToe#48]
This logic seems overly complicated for such a simple evaluation, based on its one-time use.  In fact, based on the what the value represents, you don't need it at all, once you convert the Key to Int32.

```csharp
        public static int convertAscii(int value)
        {
            if (value <= 57 && value >= 48)
            {
                value -= 48;
            }
            else if (value >= 96 && value <= 105)
            {
                value -= 96;
            }
            return value;
        }

```

**Comment by Marinarra** [comment]
This is now also being used to only allow number input while the user is choosing coordinates. I consolidated it down to one declaration of the function and it's now used in the main menu as well. (I realize now it would not be needed at all but I decided only pressing one key seemed better user interface-wise and didn't want to mismatch input formats.)
